unbind C-b
set -g prefix C-q
setw -g mode-keys vi
set -s set-clipboard off
set -g allow-passthrough off
set -g mouse on
set -g status off
set -g extended-keys on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key C-v split-window -h
bind-key C-s split-window -v
bind-key C-j resize-pane -D
bind-key C-k resize-pane -U
bind-key C-h resize-pane -L
bind-key C-l resize-pane -R
bind-key X kill-pane

