[language-server.clangd]
command = "clangd-22"
args = ["--enable-config"]

[language-server.pyrefly]
command = "pyrefly"
args = ["lsp", "-j", "24"]

[language-server.ruff]
command = "uvx"
args = ["ruff", "server"]

[language-server.rust-analyzer]
config = { check = { command = "clippy" } }
roots = ["Cargo.toml"]

[[language]]
name = "cpp"
language-servers = ["clangd"]
roots = ["compile_commands.json", ".clangd"]
formatter = { command = "clang-format", args = ["--assume-filename=file.cpp"] }
auto-format = true

[[language]]
name = "python"
roots = ["pyproject.toml", "uv.lock", ".venv"]
language-servers = ["basedpyright", "ruff"]
auto-format = true

[[language]]
name = "rust"
roots = ["Cargo.toml", "rust-project.json"]
language-servers = ["rust-analyzer"]
formatter = { command = "rustfmt", args = ["--edition", "2024"] }
auto-format = true

[formatters.rust]
command = "cargo"
args = ["fmt", "--", "--emit", "files"]
